### ISSUE TITLE
SECTION_AWS_ACCOUNT

### ISSUE THREAD

**Issue by matiasbraun** [nfscan/ocr-process-service#4]
First, great project!

i am in doubt what value to fill in SECTION_AWS_ACCOUNT, in /util/config.py

i've tried:  
arn:aws:iam::***********_:user/nfscan_development
nfscan_development
my aws account id ***_********

created /etc/boto.cfg with my account id and access key
no luck.
any advice?

**Comment by PauloMigAlmeida** [comment]
Hi @matiasbraun 

Thanks for you compliments, I'm still on the process of documenting this project to make it as easy as possible to use.

Regarding to this questions I thought this could be a good way to explain how things work on `ocr-process-service` project.
- `ocr-process-service` uses boto as its way to communicate with AWS services. So you do can configure `boto` the way that fits best to you as described on [their documentation](http://boto.readthedocs.org/en/latest/boto_config_tut.html).
- the util/config.py file is a `ocr-process-service` file and it assumes you have already a working boto configuration file. It reads a file from `/etc/ocr-process-service/ocr-process-service.cfg` on your operational system. So you have two options: Either you move the template file located under the same path in this project to this location or you change this line to the place you have `ocr-process-service.cfg`. https://github.com/nfscan/ocr-process-service/blob/master/util/config.py#L17
- on the ocr-process-service.cfg all you have to do is to set the values from your AWS resources. Basically it needs to know in which region you have configured the SQS queues and S3 bucket. It's very likely that if you have followed the previous [set up walkthrough](https://github.com/nfscan/nfscan/wiki/Develpment-environment---%5BPortuguese%5D) I've wrote on nfscan/nfscan repository that it's going to be something like this.

``` Python
[aws_account]
default_region = sa-east-1

[aws_sqs]
queue_name_in = DES-NFSCAN-OCR-PROCESS-IN
queue_name_out = DES-NFSCAN-OCR-PROCESS-OUT

[aws_s3]
bucket_name = <YourBucket>
```

Let me know if that worked for you mate

Regards
