### ISSUE TITLE
Porque a solução está acoplada na Amazon? Dá pra colocar em Docker tudo?

### ISSUE THREAD

**Issue by humbertosales** [nfscan/ocr-process-service#8]
Olá pessoal,

Primeiramente parabéns pela solução. Encontrei a solução de vocês por acaso, procurando um imagem de "notafiscal no mobile" pelo google images. rs
Show!

Não tenho familiaridade com a AWS e gostaria de saber o que preciso fazer para deixar a solução independente da Cloud que estiver usando. 

Gostaria de transformar tanto o OCR-PROCESS-SERVICE como o NFSCAN-SERVER em containers dockers, mas minha falta de conhecimento da arquitetura AWS está me travando.

Como é feita essa comunicação entre o NFSCAN-SERVER e o OCR?

**Comment by PauloMigAlmeida** [comment]
Boa tarde @humbertosales 

> Não tenho familiaridade com a AWS e gostaria de saber o que preciso fazer para deixar a solução independente da Cloud que estiver usando.

R.: Atualmente a arquitetura do nfscan (nfscan-server e o ocr-process-service) utilizam dois servicos especificos da AWS. O DynamoDB como servico de banco de dados NoSQL e o SQS como servico de mensageria. A escolha dos dois se deu pela relacao custo/beneficio quando densenhando um sistema altamente disponivel. Para tornar o projeto independente de cloud esses componentes deverao ser substituidos por seus equivalentes. Contudo, se a barreira esta na configuracao dos servicos, eu recentemente adicionei botoes do Cloudformation no arquivo readme.md do nfscan que permite que toda a infraestrutura seja montada automaticamente, diminuindo assim essa barreira no momento.

> Gostaria de transformar tanto o OCR-PROCESS-SERVICE como o NFSCAN-SERVER em containers dockers, mas minha falta de conhecimento da arquitetura AWS está me travando.

R.:  Concidentemente eu estou trabalhando na construcao de containers dockers para o nfscan nesse exato momento, porem transforma-los seria apenas um dos passos, uma vez que para manter-lo altamente disponivel eu vou ter de implementar a orquestracao do mesmo. No primeiro momento, eu estou criando as imagens dockers para utilizar a plataforma do ECS (Elastic container service) e pretendo no futuro extender para outras plataformas. Caso tenha interesse em porta-lo me avise.

> Gostaria de transformar tanto o OCR-PROCESS-SERVICE como o NFSCAN-SERVER em containers dockers, mas minha falta de conhecimento da arquitetura AWS está me travando.

R.: O nfscan utiliza um estilo arquitetural baseado em filas (Amazon SQS).
